ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(rsync golang)

# Load various config files
DFIR="$HOME/.dotfiles"

for file in "$DFIR"/{exports,aliases,functions,inits}/*.zsh
do
  source $file
done

# local environment variables
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# local extra paths, aliases, etc.
if [[ -a ~/.extras ]]
then
  source ~/.extras
fi


source $ZSH/oh-my-zsh.sh