ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(rsync golang)



# your project folder that we can `c [tab]` to
export PROJECTS=~/projects

# local environment variables
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# load from dotfiles
DOTFILES_DIR="$HOME/.dotfiles"
ALIASES_DIR="$DOTFILES_DIR/aliases"
PATHS_DIR="$DOTFILES_DIR/paths"
FUNCTIONS_DIR="$DOTFILES_DIR/paths"

# aliases
typeset -U alias_files
alias_files=($ALIASES_DIR/*.zsh)

for file in ${alias_files}
do
  source $file
done


source $ZSH/oh-my-zsh.sh