ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(rsync golang)

# local environment variables
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Load various config files
DFIR="$HOME/.dotfiles"

for file in "$DFIR"/{exports,aliases,functions,inits}/*.zsh
do
  source $file
done

source $ZSH/oh-my-zsh.sh